### ISSUE TITLE
Web Scraping | BSEE Data

### ISSUE THREAD

**Issue by vamseeachanta** [vamseeachanta/energydata#11]
Objective:  Preferred method of obtaining data (top first): 
- REQUEST/POST calls (check Scrapy and other packages)
- Selenium actions  (browser in backgroud)
- Selenium actions  (browser in foreground). data_bsee_selenium_api

When we search for API (See below screenshot), we are extracting data using below Selenium process.
https://github.com/vamseeachanta/energydata/blob/bseedata/docs/bsee_data_api.png

The data is from below website
https://www.data.boem.gov/Well/APD/Default.aspx

Note the below screenshot when searched by uniqueID is without with an uniqueID.  For this website , can we still call out a class and get json/xml format data directly?

**Comment by vamseeachanta** [comment]
![image](https://github.com/user-attachments/assets/54a54184-32d0-4837-9471-725c09e2f1a8)

**Comment by samdansk2** [comment]
@vamseeachanta Hello sir , want to give you progress regarding scraping asp webpages data 

- Based on what we have collected for scraping data for asp web page , they are also doing the same thing but using scrapy and sending requests and getting data .
- you should decide we have to follow that and improve or use existing selenium

**Comment by vamseeachanta** [comment]
@samdansk2 , 

a/ Using AI and our bsee website, prepare a module to read data using scrapy. 
b/ How well do you understand Selenium process?

Write tests with both processes. We will pick 1 based on our understanding, ease of use, code maintainability etc.

Hope this helps.

**Comment by samdansk2** [comment]
@vamseeachanta Hello sir, 
I have researched a lot regarding the best way of scrapping asp webpages data 

- Selenium is basically takes many things for the scrapping process and it is not that much smart approach 
- scrapy is mainly works on sending POST requests and getting data 
- I have found another method also i.e, Requests and beautifulsoup , please see below :

**Comment by vamseeachanta** [comment]
Excellent. 

We will develop all 3 and keep them as tests for API Well data. If effort goes out of proportion, at least develop two methods.

We will select 1 and use it for our bsee data app. Others can reside as tests. 

PS: Way to go on using AI. I can see you are using chatGPT to develop code. Keep it up.

**Comment by vamseeachanta** [comment]
Based on below. Write tests for all 3 technologies in summary below. Then decide on best.

When we do web scrapping for another repository, move WebScrapping code to AssetUtiltiies and add a class called "WebScrapping " and refer to this in all repositories.

https://github.com/vamseeachanta/assetutilities/blob/d27a230c89e7210ee47ba0ae9cb6faafa578e95e/docs/sub_web_scraping/api.md

**Comment by samdansk2** [comment]
@vamseeachanta 
Everything is going well, 
I have also added the complete code in Assetutilities . 
Only Production data in making

**Comment by samdansk2** [comment]
@vamseeachanta Gud evening sir ,
Done writing code for production data ,
thankyou

**Comment by vamseeachanta** [comment]
@samdansk2 , please take a few hours to work the documentation. i.e update the work flow chart and mark up what is done, what is pending, the method we are using etc.  If you want to do it together, let me know and happy to help.

**Comment by samdansk2** [comment]
I will start first sir , then you will improve it to further level .

**Comment by samdansk2** [comment]
scraped various data using scrapy and created documentation

**Comment by vamseeachanta** [comment]
*This was generated by AI during triage.*

**Flagged `model-rework` (2026-06-10):** KNOWLEDGE-TO-MODULE — holds the BSEE scraping method hierarchy (REQUEST/POST > background Selenium > foreground Selenium) and site-specific recipes that the scheduler refresh stack still needs. Re-executing as hardened request-based adapters would serve #267 (BSEE scheduler runtime compat), #129, and the refresh acceptance contract #462. Flag register: see triage session 2026-06-10.
