### ISSUE TITLE
BSEE | Data

### ISSUE THREAD

**Issue by vamseeachanta** [vamseeachanta/energydata#9]
Objective: Get data from bsee website for further usage (view, process, analysis, etc.)
#4 : well data story is done here.
Further data to be read, see below:

VA: Add documentation of all the potential data (Previous google documentation)

**Comment by vamseeachanta** [comment]
paleo data:
https://github.com/vamseeachanta/energydata/blob/bseedata/docs/raw_data/paleo

**Comment by vamseeachanta** [comment]
borehole data:
api: 608174149400
url: https://www.data.boem.gov/Well/Borehole/Default.aspx/

**Comment by vamseeachanta** [comment]
This is the place all the urls and data is available. See if you can get this script to run and download data. This is data intensive. Hope you have a good internet connection and hard disk space, we can have to do it someother way.

https://github.com/vamseeachanta/energydata/blob/7cdc1e006e90967d809d16a0831af7492c34f1f6/src/energydata/custom/bsee_data_refresh.py

**Comment by samdansk2** [comment]
> borehole data: api: 608174149400 url: https://www.data.boem.gov/Well/Borehole/Default.aspx/

Done sir , successfully accomplished running test file , please see below ,


![Screenshot (23)](https://github.com/user-attachments/assets/1e785944-3e33-4f50-bce6-ea860498aa6a)

**Comment by vamseeachanta** [comment]
To progress bseedata further, we need to setup and use AceEngineer Google remote desktop server.

**Comment by vamseeachanta** [comment]
Workflow of usage for BSEE:
a/ APILIST. < 1 week old -> redownload
github\energydata\data\bsee\APIRawData.zip

b/ Load into in-line (in program) database (python).
https://www.sqlalchemy.org/ or  inlinesql or other?

c/ User will ask for data for a well API 14.

d/ Use this API14 to perform other queries (online)

**Comment by vamseeachanta** [comment]
prepare plantuml and expand the workflow.

**Comment by samdansk2** [comment]
@vamseeachanta Hello sir ,
Added plantuml for workflow , test for reading zip file .

**Comment by vamseeachanta** [comment]
@samdansk2 , this is generic test. Code and test for reading zip file should go into AssetUtiliites.

**Comment by samdansk2** [comment]
@vamseeachanta good evening sir , you said to me to try for 10 API's , but where can i get API numbers sir ?

**Comment by samdansk2** [comment]
@vamseeachanta hello sir good evening , you said me to try for 10 API's , 
when i test for those , only one row of data is coming in output . so ?

**Comment by samdansk2** [comment]
these are the API's i have tested , 

![Screenshot (35)](https://github.com/user-attachments/assets/3f8023f4-bdf0-417f-be9a-2c11a456eb6e)

**Comment by vamseeachanta** [comment]
Looks good. Please add a variety of them as tests in our library.

**Comment by vamseeachanta** [comment]
eg.. test_bsee_well_data_api_number (or) rejig a test file to get through multiple APIs as an array in 1 test file.

figure out your architecture. But keep your program as modular as possible. i.e. looping through a list should be on the very outside and we should be able to change that portion easily.

**Comment by vamseeachanta** [comment]
As mentioned, we need to get all data through url route first.
If data not found, we resort to downloaded -> load -> extract required data using queries. 

Downloaded data can go stale easily. Online query data will always be most up to date.

**Comment by samdansk2** [comment]
@vamseeachanta 
I think thi will be useful for us , 
https://blog.hubspot.com/website/ai-web-scraping#what-is-an-ai-web-scraper

**Comment by vamseeachanta** [comment]
@samdansk2 , I read the hubspot article. It was worth reading and understanding what people are doing. There is no guaranteed solution it will work for us. Even if it works, we have to go through an integration with our program as an open source for anyone to use. Cost, licensing and too many hurdles to go ahead. 

RealPython scraper example is what I suggested JC when he was working on. He should have followed below or found a completely different solution in Selenium:
https://realpython.com/beautiful-soup-web-scraper-python/

**Comment by vamseeachanta** [comment]
We should attack this in 2 pronged manner:
a/ understand how BSEE recommending to use their data website. See below:
https://www.data.bsee.gov/Main/Tutorials/Default.aspx
b/ Understand the python technologies out there to send online queries. JC has developed one of the online query method by using Selenium (i.e. manually go through operations)

**Comment by vamseeachanta** [comment]
**Understanding Data Source:**
When we search for API, the url is still nuetral. But there must be a suburl in side the page that will change and give the result. Can we find that URL?

![image](https://github.com/user-attachments/assets/54a54184-32d0-4837-9471-725c09e2f1a8)

**Comment by vamseeachanta** [comment]
@samdansk2 , please separate this to 2 issues as follows:
a/ BSEE Data Source | Spike
b/ Data API | Spike

**Comment by vamseeachanta** [comment]
added existing JC's process below:
https://github.com/vamseeachanta/energydata/blob/bseedata/docs/bsee_data_api.puml

**Comment by samdansk2** [comment]
@vamseeachanta done sir , added the remaining process

**Comment by vamseeachanta** [comment]
A brief data status update. We have written python code to get following data by Well API12 Number.


A brief overview is also given in link below:

**Comment by samdansk2** [comment]
old issue of scraping process , not necessary for now

**Comment by vamseeachanta** [comment]
*This was generated by AI during triage.*

**Flagged `model-rework` (2026-06-10):** KNOWLEDGE-TO-MODULE — 23-comment master thread cataloging BSEE/BOEM data sources (paleo fixed-width ASCII, borehole, APIRawData workflow, zip-download recipes) executed manually in the intern era. Re-executing into documented, tested ingest adapters would serve #365/#366 (binary-tier + HSE bulk ingest) and the analytics epic #423. Flag register: see triage session 2026-06-10.
